apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "template-home-service.fullname" . }}
  labels:
    {{- include "template-home-service.labels" . | nindent 4 }}
data:
  application.yml: |
    spring:
      application:
        name: template-home-service
    server:
      port: {{ .Values.service.targetPort }}
    management:
      endpoints:
        web:
          exposure:
            include: health,info,prometheus,metrics
