apiVersion: v1
kind: Secret
metadata:
  name: {{ include "template-home-service.fullname" . }}-db
  labels:
    {{- include "template-home-service.labels" . | nindent 4 }}
type: Opaque
data:
  username: {{ .Values.postgresql.auth.username | b64enc | quote }}
  password: {{ .Values.postgresql.auth.password | b64enc | quote }}
